author: Dif # 作者
description: Dif's blog
keyword: hexo-theme, vuejs
home_img: /css/images/home-bg.jpg
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

comment: gitment

# gitment config
gitment_owner: chendingfeng
gitment_repo: chendingfeng.github.io
#gitment_oauth_id: 0f87e490e00ee3fd87ef
#gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 

# disqus config
disqus_shortname: 

about: 
  banner: /css/images/about.jpg
  avatar: /css/images/avatar.png
  description: "每天2.5L水"
  #weibo_username: chendingfeng
  #twitter_username: chendingfeng
  github_username: chendingfeng
  #zhihu_username: chendingfeng
  #douban_username: chendingfeng
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
